/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UlubioneRouteImport } from './routes/ulubione'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProduktyRouteImport } from './routes/produkty'
import { Route as KoszykRouteImport } from './routes/koszyk'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduktSlugRouteImport } from './routes/produkt.$slug'
import { Route as KategoriaSlugRouteImport } from './routes/kategoria.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminZamowieniaRouteImport } from './routes/_authenticated/admin.zamowienia'
import { Route as AuthenticatedAdminUstawieniaRouteImport } from './routes/_authenticated/admin.ustawienia'
import { Route as AuthenticatedAdminStatystykiRouteImport } from './routes/_authenticated/admin.statystyki'
import { Route as AuthenticatedAdminPromocjeRouteImport } from './routes/_authenticated/admin.promocje'
import { Route as AuthenticatedAdminProduktyRouteImport } from './routes/_authenticated/admin.produkty'
import { Route as AuthenticatedAdminMarkiRouteImport } from './routes/_authenticated/admin.marki'
import { Route as AuthenticatedAdminKategorieRouteImport } from './routes/_authenticated/admin.kategorie'
import { Route as AuthenticatedAdminProduktyNowyRouteImport } from './routes/_authenticated/admin.produkty.nowy'
import { Route as AuthenticatedAdminProduktyIdRouteImport } from './routes/_authenticated/admin.produkty.$id'

const UlubioneRoute = UlubioneRouteImport.update({
  id: '/ulubione',
  path: '/ulubione',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktyRoute = ProduktyRouteImport.update({
  id: '/produkty',
  path: '/produkty',
  getParentRoute: () => rootRouteImport,
} as any)
const KoszykRoute = KoszykRouteImport.update({
  id: '/koszyk',
  path: '/koszyk',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktSlugRoute = ProduktSlugRouteImport.update({
  id: '/produkt/$slug',
  path: '/produkt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriaSlugRoute = KategoriaSlugRouteImport.update({
  id: '/kategoria/$slug',
  path: '/kategoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminZamowieniaRoute =
  AuthenticatedAdminZamowieniaRouteImport.update({
    id: '/zamowienia',
    path: '/zamowienia',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUstawieniaRoute =
  AuthenticatedAdminUstawieniaRouteImport.update({
    id: '/ustawienia',
    path: '/ustawienia',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStatystykiRoute =
  AuthenticatedAdminStatystykiRouteImport.update({
    id: '/statystyki',
    path: '/statystyki',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromocjeRoute =
  AuthenticatedAdminPromocjeRouteImport.update({
    id: '/promocje',
    path: '/promocje',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProduktyRoute =
  AuthenticatedAdminProduktyRouteImport.update({
    id: '/produkty',
    path: '/produkty',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarkiRoute = AuthenticatedAdminMarkiRouteImport.update({
  id: '/marki',
  path: '/marki',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminKategorieRoute =
  AuthenticatedAdminKategorieRouteImport.update({
    id: '/kategorie',
    path: '/kategorie',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProduktyNowyRoute =
  AuthenticatedAdminProduktyNowyRouteImport.update({
    id: '/nowy',
    path: '/nowy',
    getParentRoute: () => AuthenticatedAdminProduktyRoute,
  } as any)
const AuthenticatedAdminProduktyIdRoute =
  AuthenticatedAdminProduktyIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminProduktyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/checkout': typeof CheckoutRoute
  '/koszyk': typeof KoszykRoute
  '/produkty': typeof ProduktyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ulubione': typeof UlubioneRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/kategoria/$slug': typeof KategoriaSlugRoute
  '/produkt/$slug': typeof ProduktSlugRoute
  '/admin/kategorie': typeof AuthenticatedAdminKategorieRoute
  '/admin/marki': typeof AuthenticatedAdminMarkiRoute
  '/admin/produkty': typeof AuthenticatedAdminProduktyRouteWithChildren
  '/admin/promocje': typeof AuthenticatedAdminPromocjeRoute
  '/admin/statystyki': typeof AuthenticatedAdminStatystykiRoute
  '/admin/ustawienia': typeof AuthenticatedAdminUstawieniaRoute
  '/admin/zamowienia': typeof AuthenticatedAdminZamowieniaRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/produkty/$id': typeof AuthenticatedAdminProduktyIdRoute
  '/admin/produkty/nowy': typeof AuthenticatedAdminProduktyNowyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/checkout': typeof CheckoutRoute
  '/koszyk': typeof KoszykRoute
  '/produkty': typeof ProduktyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ulubione': typeof UlubioneRoute
  '/kategoria/$slug': typeof KategoriaSlugRoute
  '/produkt/$slug': typeof ProduktSlugRoute
  '/admin/kategorie': typeof AuthenticatedAdminKategorieRoute
  '/admin/marki': typeof AuthenticatedAdminMarkiRoute
  '/admin/produkty': typeof AuthenticatedAdminProduktyRouteWithChildren
  '/admin/promocje': typeof AuthenticatedAdminPromocjeRoute
  '/admin/statystyki': typeof AuthenticatedAdminStatystykiRoute
  '/admin/ustawienia': typeof AuthenticatedAdminUstawieniaRoute
  '/admin/zamowienia': typeof AuthenticatedAdminZamowieniaRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/produkty/$id': typeof AuthenticatedAdminProduktyIdRoute
  '/admin/produkty/nowy': typeof AuthenticatedAdminProduktyNowyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/authorize': typeof AuthorizeRoute
  '/checkout': typeof CheckoutRoute
  '/koszyk': typeof KoszykRoute
  '/produkty': typeof ProduktyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ulubione': typeof UlubioneRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/kategoria/$slug': typeof KategoriaSlugRoute
  '/produkt/$slug': typeof ProduktSlugRoute
  '/_authenticated/admin/kategorie': typeof AuthenticatedAdminKategorieRoute
  '/_authenticated/admin/marki': typeof AuthenticatedAdminMarkiRoute
  '/_authenticated/admin/produkty': typeof AuthenticatedAdminProduktyRouteWithChildren
  '/_authenticated/admin/promocje': typeof AuthenticatedAdminPromocjeRoute
  '/_authenticated/admin/statystyki': typeof AuthenticatedAdminStatystykiRoute
  '/_authenticated/admin/ustawienia': typeof AuthenticatedAdminUstawieniaRoute
  '/_authenticated/admin/zamowienia': typeof AuthenticatedAdminZamowieniaRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/produkty/$id': typeof AuthenticatedAdminProduktyIdRoute
  '/_authenticated/admin/produkty/nowy': typeof AuthenticatedAdminProduktyNowyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authorize'
    | '/checkout'
    | '/koszyk'
    | '/produkty'
    | '/sitemap.xml'
    | '/ulubione'
    | '/admin'
    | '/kategoria/$slug'
    | '/produkt/$slug'
    | '/admin/kategorie'
    | '/admin/marki'
    | '/admin/produkty'
    | '/admin/promocje'
    | '/admin/statystyki'
    | '/admin/ustawienia'
    | '/admin/zamowienia'
    | '/admin/'
    | '/admin/produkty/$id'
    | '/admin/produkty/nowy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authorize'
    | '/checkout'
    | '/koszyk'
    | '/produkty'
    | '/sitemap.xml'
    | '/ulubione'
    | '/kategoria/$slug'
    | '/produkt/$slug'
    | '/admin/kategorie'
    | '/admin/marki'
    | '/admin/produkty'
    | '/admin/promocje'
    | '/admin/statystyki'
    | '/admin/ustawienia'
    | '/admin/zamowienia'
    | '/admin'
    | '/admin/produkty/$id'
    | '/admin/produkty/nowy'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/authorize'
    | '/checkout'
    | '/koszyk'
    | '/produkty'
    | '/sitemap.xml'
    | '/ulubione'
    | '/_authenticated/admin'
    | '/kategoria/$slug'
    | '/produkt/$slug'
    | '/_authenticated/admin/kategorie'
    | '/_authenticated/admin/marki'
    | '/_authenticated/admin/produkty'
    | '/_authenticated/admin/promocje'
    | '/_authenticated/admin/statystyki'
    | '/_authenticated/admin/ustawienia'
    | '/_authenticated/admin/zamowienia'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/produkty/$id'
    | '/_authenticated/admin/produkty/nowy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthorizeRoute: typeof AuthorizeRoute
  CheckoutRoute: typeof CheckoutRoute
  KoszykRoute: typeof KoszykRoute
  ProduktyRoute: typeof ProduktyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UlubioneRoute: typeof UlubioneRoute
  KategoriaSlugRoute: typeof KategoriaSlugRoute
  ProduktSlugRoute: typeof ProduktSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ulubione': {
      id: '/ulubione'
      path: '/ulubione'
      fullPath: '/ulubione'
      preLoaderRoute: typeof UlubioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkty': {
      id: '/produkty'
      path: '/produkty'
      fullPath: '/produkty'
      preLoaderRoute: typeof ProduktyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koszyk': {
      id: '/koszyk'
      path: '/koszyk'
      fullPath: '/koszyk'
      preLoaderRoute: typeof KoszykRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkt/$slug': {
      id: '/produkt/$slug'
      path: '/produkt/$slug'
      fullPath: '/produkt/$slug'
      preLoaderRoute: typeof ProduktSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategoria/$slug': {
      id: '/kategoria/$slug'
      path: '/kategoria/$slug'
      fullPath: '/kategoria/$slug'
      preLoaderRoute: typeof KategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/zamowienia': {
      id: '/_authenticated/admin/zamowienia'
      path: '/zamowienia'
      fullPath: '/admin/zamowienia'
      preLoaderRoute: typeof AuthenticatedAdminZamowieniaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ustawienia': {
      id: '/_authenticated/admin/ustawienia'
      path: '/ustawienia'
      fullPath: '/admin/ustawienia'
      preLoaderRoute: typeof AuthenticatedAdminUstawieniaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/statystyki': {
      id: '/_authenticated/admin/statystyki'
      path: '/statystyki'
      fullPath: '/admin/statystyki'
      preLoaderRoute: typeof AuthenticatedAdminStatystykiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promocje': {
      id: '/_authenticated/admin/promocje'
      path: '/promocje'
      fullPath: '/admin/promocje'
      preLoaderRoute: typeof AuthenticatedAdminPromocjeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/produkty': {
      id: '/_authenticated/admin/produkty'
      path: '/produkty'
      fullPath: '/admin/produkty'
      preLoaderRoute: typeof AuthenticatedAdminProduktyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/marki': {
      id: '/_authenticated/admin/marki'
      path: '/marki'
      fullPath: '/admin/marki'
      preLoaderRoute: typeof AuthenticatedAdminMarkiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kategorie': {
      id: '/_authenticated/admin/kategorie'
      path: '/kategorie'
      fullPath: '/admin/kategorie'
      preLoaderRoute: typeof AuthenticatedAdminKategorieRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/produkty/nowy': {
      id: '/_authenticated/admin/produkty/nowy'
      path: '/nowy'
      fullPath: '/admin/produkty/nowy'
      preLoaderRoute: typeof AuthenticatedAdminProduktyNowyRouteImport
      parentRoute: typeof AuthenticatedAdminProduktyRoute
    }
    '/_authenticated/admin/produkty/$id': {
      id: '/_authenticated/admin/produkty/$id'
      path: '/$id'
      fullPath: '/admin/produkty/$id'
      preLoaderRoute: typeof AuthenticatedAdminProduktyIdRouteImport
      parentRoute: typeof AuthenticatedAdminProduktyRoute
    }
  }
}

interface AuthenticatedAdminProduktyRouteChildren {
  AuthenticatedAdminProduktyIdRoute: typeof AuthenticatedAdminProduktyIdRoute
  AuthenticatedAdminProduktyNowyRoute: typeof AuthenticatedAdminProduktyNowyRoute
}

const AuthenticatedAdminProduktyRouteChildren: AuthenticatedAdminProduktyRouteChildren =
  {
    AuthenticatedAdminProduktyIdRoute: AuthenticatedAdminProduktyIdRoute,
    AuthenticatedAdminProduktyNowyRoute: AuthenticatedAdminProduktyNowyRoute,
  }

const AuthenticatedAdminProduktyRouteWithChildren =
  AuthenticatedAdminProduktyRoute._addFileChildren(
    AuthenticatedAdminProduktyRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminKategorieRoute: typeof AuthenticatedAdminKategorieRoute
  AuthenticatedAdminMarkiRoute: typeof AuthenticatedAdminMarkiRoute
  AuthenticatedAdminProduktyRoute: typeof AuthenticatedAdminProduktyRouteWithChildren
  AuthenticatedAdminPromocjeRoute: typeof AuthenticatedAdminPromocjeRoute
  AuthenticatedAdminStatystykiRoute: typeof AuthenticatedAdminStatystykiRoute
  AuthenticatedAdminUstawieniaRoute: typeof AuthenticatedAdminUstawieniaRoute
  AuthenticatedAdminZamowieniaRoute: typeof AuthenticatedAdminZamowieniaRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminKategorieRoute: AuthenticatedAdminKategorieRoute,
  AuthenticatedAdminMarkiRoute: AuthenticatedAdminMarkiRoute,
  AuthenticatedAdminProduktyRoute: AuthenticatedAdminProduktyRouteWithChildren,
  AuthenticatedAdminPromocjeRoute: AuthenticatedAdminPromocjeRoute,
  AuthenticatedAdminStatystykiRoute: AuthenticatedAdminStatystykiRoute,
  AuthenticatedAdminUstawieniaRoute: AuthenticatedAdminUstawieniaRoute,
  AuthenticatedAdminZamowieniaRoute: AuthenticatedAdminZamowieniaRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthorizeRoute: AuthorizeRoute,
  CheckoutRoute: CheckoutRoute,
  KoszykRoute: KoszykRoute,
  ProduktyRoute: ProduktyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UlubioneRoute: UlubioneRoute,
  KategoriaSlugRoute: KategoriaSlugRoute,
  ProduktSlugRoute: ProduktSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
